version: '3.8'

services:
  fastapi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    container_name: fastapi
    expose:
      - "8000" 
    networks:
      - app-network  
    restart: always

  react:
    build:
      context: .
      dockerfile: React/Diagnostics-app/Dockerfile
    expose:
      - "80" 
    depends_on: 
      - fastapi
    networks:
      - app-network  
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - react
    networks:
      - app-network  
    restart: always

networks:
  app-network:
    driver: bridge  
