version: '3.8'

services:
  fastapi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    expose:
      - "8000" 
    networks:
      - app-network  

  react:
    build:
      context: .
      dockerfile: React/Diagnostics-app/Dockerfile
    expose:
      - "80" 
    networks:
      - app-network  

  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - react
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge  
