
services:
  fastapi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    container_name: fastapi
    networks:
      - app-network
    restart: always
    ports:
      - "8000"

  nginx-react:
    container_name: nginxreactapp
    build:
      context: .
      dockerfile: React/Diagnostics-app/Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
