version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    expose:
      - "8000"  
    network_mode: host 

  react:
    build:
      context: .
      dockerfile: React/Diagnostics-app/Dockerfile  
    expose:
      - "80"  
    network_mode: host  

  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: nginx/Dockerfile  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
    ports:
      - "80:80"  
    depends_on:
      - fastapi  
      - react   
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge  
