version: '3.8'

services:
  fastapi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: FastAPI/Dockerfile
    container_name: fastapi
    expose:
      - "8000" 
    networks:
      - app-network  
    restart: always
    
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: React/Diagnostics-app/Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - fastapi
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge  
